# Generated by Django 3.0.7 on 2020-06-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=30)),
                ('qnt_produto', models.IntegerField(max_length=4)),
                ('valor_produto', models.FloatField(max_length=6)),
                ('tipo_opcional', models.CharField(choices=[('info', 'informatica'), ('food', 'comida'), ('home', 'escritorio')], max_length=10)),
            ],
        ),
    ]
