# Generated by Django 3.0.7 on 2020-06-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='produtos',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
