# Generated by Django 3.0.7 on 2020-06-29 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20200628_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='qnt_produto',
            field=models.IntegerField(),
        ),
    ]
